  @startuml
object CarePlan

object Identifier
object Reference
object Patient
object Group
object Encounter
object EpisodeOfCare
object Period
object Practitioner
object RelatedPerson
object Organization
object CodeableConcept
object Condition
object Goal
object Appointment
object CommunicationRequest
object DeviceUseRequest
object DiagnosticOrder
object MedicationOrder
object NutritionOrder
object Order
object ProcedureRequest
object ProcessRequest
object ReferralRequest
object ProceduresRequest
object SupplyRequest
object VisionPrescription
object Location
object Medication
object Substance
object Quantity

CarePlan -- Identifier
CarePlan -- Reference
CarePlan -- Patient
CarePlan -- Group
CarePlan -- Encounter
CarePlan -- EpisodeOfCare
CarePlan -- Period
CarePlan -- Practitioner
CarePlan -- RelatedPerson
CarePlan -- Organization
CarePlan -- CodeableConcept
CarePlan -- Condition
CarePlan -- Goal
CarePlan -- Appointment
CarePlan -- CommunicationRequest
CarePlan -- DeviceUseRequest

DiagnosticOrder -- CarePlan
MedicationOrder -- CarePlan
NutritionOrder -- CarePlan
Order -- CarePlan
ProcedureRequest -- CarePlan
ReferralRequest -- CarePlan
SupplyRequest -- CarePlan
ProceduresRequest -- CarePlan
ProcessRequest -- CarePlan
VisionPrescription -- CarePlan
Location -- CarePlan
Medication -- CarePlan
Substance -- CarePlan
Quantity -- CarePlan
CarePlan -- CarePlan
@enduml
