@startuml
object Appointment

Appointment : resourceType
Appointment : id
Appointment : text
Appointment : identifier
Appointment : status
Appointment : type
Appointment : reason
Appointment : start
Appointment : end
Appointment : priority
Appointment : description
Appointment : minutesDuration
Appointment : slot
Appointment : comment
Appointment : participant

object Communication

Communication : resourceType
Communication : id
Communication : text
Communication : identifier
Communication : medium
Communication : category
Communication : sender
Communication : recipient
Communication : payload
Communication : status
Communication : contentReference
Communication : sent
Communication : subject

object Device

Device : resourceType
Device : type
Device : model
Device : identifier
Device : note

object FinnishPatient

FinnishPatient : identifier
FinnishPatient : active
FinnishPatient : communication

object Person

Person : identifier
Person : active
Person : name
Person : telecom
Person : gender
Person : birthDate
Person : address
Person : photo
Person : managingOrganization

object CarePlan
CarePlan : identifier
CarePlan : subject
CarePlan : status
CarePlan : context
CarePlan : period
CarePlan : author
CarePlan : modified
CarePlan : category
CarePlan : description
CarePlan : addresses
CarePlan : support
CarePlan : goal
CarePlan : note
CarePlan : relatedPlan
CarePlan : participant
CarePlan : activity


object CareTeam
CareTeam : identifier
CareTeam : status
CareTeam : category
CareTeam : name
CareTeam : subject
CareTeam : period
CareTeam : participant
CareTeam : managingOrganization


object Goal
Goal : identifier
Goal : subject
Goal : start[x]
Goal : target[x]
Goal : category
Goal : description
Goal : status
Goal : statusDate
Goal : statusReason
Goal : author
Goal : priority
Goal : addresses
Goal : note
Goal : outcome


Person -- FinnishPatient
Person -- Device
Person -- Appointment

CarePlan -- FinnishPatient
CarePlan -- Appointment
CarePlan -- Communication
CarePlan -- CareTeam
CarePlan -- Goal
@enduml
