@startuml
object  Device

object Identifier
object CodeableConcept
object DeviceKind
object Annotation
object Reference
object Organization
object Location
object Patient

Device -- Identifier
Device -- CodeableConcept
Device -- DeviceKind
Device -- Annotation
Device -- DeviceStatus
Device -- Reference
Device -- Organization
Device -- Location
Device -- Patient
@enduml
