@startuml

'!includeurl https://raw.githubusercontent.com/omahoito/rfc/master/Styles.iuml

set namespaceSeparator ::

class MVP::Person {
Reference<Patient | Practitioner> link.target
}
class MVP::Patient
class MVP::Observation {
Reference<Patient> subject
Reference<QuestionnaireResponse> related
}
class MVP::CarePlan {
Reference<Patient> subject
Reference<CareTeam> careteam
Reference<EpisodeOfCare> context
Reference<Any> support
}
class MVP::Questionnaire
class MVP::QuestionnaireResponse {
Reference<Patient> source
Reference<Questionnaire> questionnaire
}
class MVP::CareTeam {
Reference<Practitioner> participant
Reference<Organization> participant
}
class MVP::Practitioner {

}
class MVP::Communication {
Reference<Any> basedOn
}

class AllergyIntolerance {
Reference<Patient> patient
}

class Immunization {
Reference<Patient> patient
}

class MVP::MedicationStatement {
Reference<Patient> subject
}

class Flag {
Reference<Patient> subject
}

class MVP::ActivityDefinition {

}

class Medication

class MVP::EpisodeOfCare {
    status
    Reference<Practitioner> careManager
    Reference<CareTeam> team
    }

class MVP::Goal {
    description
}

class MVP::Organization {
}


hide methods
hide circle

MVP::CarePlan "0..*" -- "0..*" MVP::CareTeam : Authorization
MVP::CareTeam "0..*" -- "0..*" MVP::EpisodeOfCare : Team participating to care
MVP::CareTeam "0..*" -- "0..*" MVP::Organization

MVP::EpisodeOfCare "0..*" -- "1" MVP::Practitioner : careManager
MVP::EpisodeOfCare -- MVP::CarePlan : < context
MVP::EpisodeOfCare "*" -- "1" MVP::Patient : patient >

MVP::CarePlan "1" -- "0..*" MVP::Goal

MVP::Person "1"--"0..1" MVP::Patient
MVP::Person "1"--"0..1" MVP::Practitioner

MVP::CarePlan "0..*"--"1" MVP::Patient
MVP::CarePlan "0..*"--"0..*" MVP::QuestionnaireResponse
MVP::CarePlan "0..*"--"0..*" AllergyIntolerance
MVP::CarePlan "0..*"--"0..*" MVP::MedicationStatement
MVP::CarePlan "0..*"--"0..*" Immunization
MVP::CarePlan "0..*"--"0..*" Flag
MVP::CarePlan "0..*"--"0..*" MVP::ActivityDefinition

MVP::CareTeam "0..*"--"0..*" MVP::Practitioner

MVP::Observation "0..*"--"0..*" MVP::CarePlan
MVP::Observation "0..*"--"1" MVP::Patient
MVP::Observation "0..*"--"0..1" MVP::QuestionnaireResponse

MVP::QuestionnaireResponse "0..*"--"1" MVP::Patient
MVP::QuestionnaireResponse "0..*"--"1" MVP::Questionnaire

MVP::Communication "0..*" -- "0..1" MVP::CarePlan

AllergyIntolerance "0..*" -- "1" MVP::Patient
MVP::Patient "1"--"0..*" MVP::MedicationStatement
MVP::Patient "1"--"0..*" Immunization
MVP::Patient "1"--"0..*" Flag


MVP::MedicationStatement "0..*" -- "1" Medication

@enduml
