@startuml

header
Datamodel diagram generated with plantuml.com to github.com/omahoito/rfc. \
CC-BY-4.0 City of Espoo 2017. \
To change the picture, make a pull request with changes to ODA-PHR-Datamodel.plantuml and README.md.
endheader


set namespaceSeparator ::
hide methods
hide circle


class Organization::HealthCareService {
	Reference<Organization> providedBy
	Reference<Location> location
}
class Organization::Location
class Organization::Organization

class PHRData::AllergyIntolerance {
	Reference<Patient> patient
}

class PHRData::Immunization {
	Reference<Patient> patient
}

class PHRData::MedicationStatement {
	Reference<Patient> subject
}

class PHRData::Observation {
	Reference<Patient> subject
	Reference<QuestionnaireResponse> related
}
	
class PHRData::QuestionnaireResponse {
	Reference<Patient> source
	Reference<Questionnaire> questionnaire
}

class Care::CarePlan {
	Reference<Patient> subject
	Reference<CareTeam> careteam
	Reference<EpisodeOfCare> context
	Reference<Any> supportingInfo
	Reference<PlanDefinition> definition
	Reference<ActivityDefinition> activity.detail.definition
}

class Care::CareTeam {
	Reference<Practitioner> participant
	Reference<Organization> managingOrganization
}

class Care::Communication {
	Reference<Any> topic
}

class Care::EpisodeOfCare {
   	Reference<Practitioner> careManager
   	Reference<CareTeam> team
   	Reference<Patient> patient
} 

class Care::ActivityDefinition

class Care::Goal
class Person {
	Reference<Patient | Practitioner> link.target
}

Care::CarePlan "0..*" -- "0..*" Care::CareTeam : Service request list
Care::CareTeam "0..*" -- "0..*" Care::EpisodeOfCare : Care team
Care::CarePlan "0..*" -- "0..*" PHRData : supportingInfo
Care::EpisodeOfCare "0..1" -- "1" Care::CarePlan 
Care::EpisodeOfCare "0..*" -- "1" Patient

Person "1" -up- "0..1" Patient
Person "1" --" 0..1" Practitioner

Care::EpisodeOfCare "0..*" -- "0..1" Practitioner
Care::CareTeam "0..*" -- "0..*" Practitioner
Care::CarePlan "0..*" -- "1" Patient
Care::CarePlan "1" -- "0..*" Care::Goal
PHRData::Observation "0..*"--"0..1" PHRData::QuestionnaireResponse


PHRData::QuestionnaireResponse "0..*" -- "1" Questionnaire

Care::Communication "0..*" -- "0..1" Care::CarePlan

Organization::Organization "0..*" -- "0..1" Organization::Organization : partOf
Organization::HealthCareService "0..*" -- "1" Organization::Organization
Organization::HealthCareService "1" -- "0..1" Organization::Location

PHRData::Observation "0..*" -- "1" Patient
PHRData::AllergyIntolerance "0..*" -- "1" Patient
PHRData::Immunization "0..*" -- "1" Patient
PHRData::MedicationStatement "0..*" -- "1" Patient
PHRData::QuestionnaireResponse "0..*" -- "1" Patient

Care::CareTeam -- Organization::Organization
Care::Communication "0..*" -- "0..1" PHRData
Care::CarePlan "1" -- "0..*" Care::ActivityDefinition

@enduml