@startuml

hide methods

object Appointment {
  identifier
  status
  appointmentType
  reason
  ' added description field for a human readable description
  description
  start
  end
  minutesDuration
  comment
}

object Patient {
  ' added some missing fields that are used in a patient resource
  identifier
  name
  telecom
  gender
  birthDate
  address
  communication
}

object Slot {
  identifier
  schedule
  status
  start
  end
}

object Practitioner {
  identifier
  name
  telecom
  address
  gender
  birthDate  
  photo
  communication
  ' role.organization (ODAOrganization) ... role does not exist in DSTU3 any nmore
  ' role.healthcareService (ODAHealthcareService) ... role does not exist in DSTU3 any nmore
}

object HealthcareService {
  identifier
  type
  location 
  name
  telecom
  ' characteristic -- dropped this field out at this stage; used eg. to indicate wheel chair access
  appointmentRequired
}
note bottom : "palvelutunnus" will be\ncoded in the type field

object Organization {
  ' added some missing fields that are used in a patient resource
  identifier
  active
  type
  name
  telecom
  address
}
note bottom : "oid" will be coded\nin the identifier field

object Location {
  identifier
  status
  telecom
  address
  position
}
note bottom : "cname" will be coded\nin the identifier field

object CareTeam {
}

Appointment "0..*" -left-> "0..*" Practitioner :  participant.actor
Appointment "0..*" -down-> "1" HealthcareService :  participant.actor
Appointment "0..*" -right-> "1" Patient :  participant.actor
Appointment "1" -down-> "0..*" Slot :  slot

HealthcareService "0..*" -left-> "1" Organization : providedBy
HealthcareService "0..*  " -right-> "1" Location : location

CareTeam "0..*" -right-> "0..*" Practitioner : participant.member
CareTeam "0..*" -down-> "0..*" Organization : managingOrganization

@enduml
