@startuml
object ODAAppointment{
  identifier
  status
  appointmentType
  reason
  start
  end
  minutesDuration
  comment
  participant (ODAHealthcareService | ODAPatient | ODAPractitioner )
}

ODAAppointment -- "1..*" ODAHealthcareService
ODAAppointment -- "1..*" ODAPatient
ODAAppointment -- "1..*" ODAPractitioner

object ODAHealthcareService{
  identifier
  providedBy (ODAOrganization)
  serviceName
  telecom
  characteristic
  appointmentRequired
}

ODAHealthcareService -- "1..*" ODAOrganization

object ODAOrganization{
  identifier
  type
  name
}

object ODAPatient{
  identifier
  communication
}

object ODAPractitioner{
  identifier
  name
  telecom
  address
  gender
  birthDate  
  photo
  role.organization (ODAOrganization)
  role.healthcareService (ODAHealthcareService)
  communication
}

ODAPractitioner -- "..*" ODAOrganization
ODAPractitioner -- "..*" ODAHealthcareService
@enduml
