@startuml
object Communication

Communication : identifier

object Identifier
object CodeableConcept
object Reference
object Device
object Organization
object Patient
object Practitioner
object RelatedPerson
object Group
object Attachment
object Encounter
object CommunicationRequest

Communication -- Identifier
Communication -- CodeableConcept
Communication -- Reference
Communication -- Device
Communication -- Organization
Communication -- Patient
Communication -- Practitioner
Communication -- RelatedPerson
Communication -- Group
Communication -- Attachment
Communication -- Encounter
Communication -- CommunicationRequest
@enduml
