@startuml
object  Patient

object Identifier
object HumanName
object ContactPoint
object Address
object CodeableConcept
object Attachment
object Reference
object Organization
object Period
object Practitioner

Patient -- Identifier
Patient -- HumanName
Patient -- ContactPoint
Patient -- Address
Patient -- CodeableConcept
Patient -- Attachment
Patient -- Reference
Patient -- Organization
Patient -- Period
Patient -- Practitioner
@enduml
