@startuml
object PatientCitizen{
    identifier
    name
    telecom
    gender
    birthDate
    address
    photo
    managingOrganization
    active
    link (Device)
}

object CareTeam{
    identifier
    status
    category
    name
    subject (Patient)
    period
    participant
    participant.role
    participant.member
    participant.period
    managingOrganization
}

object CarePlan{
    id
    subject (Patient)
    status
    context
    period
    author
    careteam (CareTeam)
    addresses
    support
    modified
    relatedPlan
    goal
    category
    description
    Activity.detail.category
    Activity.detail.code.coding.system
    Activity.detail.code.coding.code
    Activity.detail.status
    Activity.detail.statusReason
    Activity.detail.prohibited
    Activity.detail.scheduled
    Activity.detail.description
    Note
}


object Communication_Message{
    identifier
    status
    category
    medium
    subject (Patient)
    topic
    context
    sent
    received
    sender
    recipient
    reason
    payload    
}

object Device{
    type
    model
    identifier
    note
}

object Appointment{
    identifier
    status
    type
    reason
    start
    end
    priority
    description
    minutesDuration
    slot
    comment
    participant (PatientCitizen | Device )
    participant.required
    participant.status
}

PatientCitizen -- "0..*" Device
PatientCitizen "1..*" -- Appointment

PatientCitizen "1..1" -- "*" CarePlan

CarePlan -- "0..*" CareTeam
CarePlan "1" -- "*" Communication_Message

CareTeam -- "0..1" PatientCitizen

@enduml
